# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: pkg build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Upload Win Asset
      # You may pin to the exact commit or the version.
      # uses: PeerXu/upload-asset@ac15234d94a4bfc9b33e1e98573fb470553ed809
      uses: PeerXu/upload-asset@v1
      with:
        # which file to upload
        file: build/geri-win.exe
        # file suffix
        suffix: .exe # optional, default is .tar.gz
        # which operating system platform for file to execute
        os: windows # optional, default is 
        # which architecture platform for file to execute
        arch: x64 # optional, default is 
        # upload file to asset with tag version
        with_tag: true # optional, default is true
        # upload file to asset with hash in sha1 algorithm
        with_sha1: true # optional, default is true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Linux Asset
      # You may pin to the exact commit or the version.
      # uses: PeerXu/upload-asset@ac15234d94a4bfc9b33e1e98573fb470553ed809
      uses: PeerXu/upload-asset@v1
      with:
        # which file to upload
        file: build/geri-linux
        # file suffix
        #suffix: .exe # optional, default is .tar.gz
        # which operating system platform for file to execute
        os: linux # optional, default is 
        # which architecture platform for file to execute
        arch: x64 # optional, default is 
        # upload file to asset with tag version
        with_tag: true # optional, default is true
        # upload file to asset with hash in sha1 algorithm
        with_sha1: true # optional, default is true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload MacOS Asset
      # You may pin to the exact commit or the version.
      # uses: PeerXu/upload-asset@ac15234d94a4bfc9b33e1e98573fb470553ed809
      uses: PeerXu/upload-asset@v1
      with:
        # which file to upload
        file: build/geri-macos
        # file suffix
        #suffix: .exe # optional, default is .tar.gz
        # which operating system platform for file to execute
        os: macos # optional, default is 
        # which architecture platform for file to execute
        arch: x64 # optional, default is 
        # upload file to asset with tag version
        with_tag: true # optional, default is true
        # upload file to asset with hash in sha1 algorithm
        with_sha1: true # optional, default is true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
