# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: pkg build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: 'Upload Windows Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: geri-win-x64.exe
        path: build/geri-win.exe
    - name: 'Upload Linux Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: geri-linux-x64
        path: build/geri-linux
    - name: 'Upload MacOS Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: geri-macos-x64
        path: build/geri-macos   
    - name: 'change version'
      uses: polygon-software/npm-version-date@master
      with:
        schema: 'yyyy.MM.V.dd.P'
        V: '1'
        increase-patch: true
    - uses: gagle/package-version@master
      id: package-version
    - name: Tag and Release
      uses: jasondavis303/tag-and-release-and-upload@v1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
        # Use the version from the previous step
        version: v${{ steps.package-version.outputs.version }}
        
        assets: '[ "build/geri-win.exe", "build/geri-macos", "build/geri-linux", "example.config.js" ]'
        overwrite: false
    #name: run npm-version pipeline
